platform :ios,'9.0'
inhibit_all_warnings!

#账号：15859359999
#密码：123456
#
#账号：15066655192
#密码：123456

# 状态为审核中  判断 state 99 98
# 19999999999
# 123456

# 19988888888 状态为未申请
# 123456

target 'zxMerchant' do
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'YYModel'
  pod 'Masonry'
  pod 'AliyunOSSiOS' ,'= 2.10.7'
  pod 'JPush'
  pod 'TZImagePickerController'
  # U-Share SDK
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  # 微信
  pod 'WechatOpenSDK'
  # bug监听
  pod 'Bugly'
  # 播放器
  pod 'CLPlayer'
  pod 'BRPickerView'
end
